### ISSUE TITLE
温度センサーの動作

### ISSUE THREAD

**Issue by WhiteHawk-taka** [chirimen-oh/echigo-examples#10]
LM60BIZ(TO-92)/LM60CIM(SOT-23)の動作
ic2-ADT7410のサンプル
+VSをCN1-1
VOUTをCN2-11
に接続することにより一定値（36540.1796875）の取得に成功

**Comment by WhiteHawk-taka** [comment]
CN2-11を抜いても値に変化がないため値が取れたとは言えないことが判明

**Comment by ghost** [comment]
ADT7410はI2Cバスに接続する温度センサですが、LM60はI2Cバス接続ではない、ですよね？

部品は、規格の適合するバス(ピン)に接続する必要があります。規格と異なるものを接続した場合、部品やCHIRIMENが壊れる可能性がありますので、ご注意ください。
